### ISSUE TITLE
Failed to make setup to run dgl model 

### ISSUE THREAD

**Issue by rankovicmiona** [ATOMconsortium/AMPL#139]
Hi,

I'm trying to make setup for running dgl (I followed the [instructions](https://github.com/ATOMScience-org/AMPL#install) for installation completely). When I try to run `source set_dgl_env.sh $test_env`, the error message that's returned is `bash: module: command not found`.

Can anybody help?

**Comment by stewarthe6** [comment]
Hello, at Livermore we use the `module` [command ](https://linux.die.net/man/1/module) to help manage environments. It modifies the environment to CUDA 11.1. I believe you can comment that out or replace it with whatever you need to do to ensure you're using CUDA 11.1.

Does this help?

**Comment by rankovicmiona** [comment]
Sure, thanks!

**Comment by mauvais2** [comment]
Hi,

Some models use dgl which requires CUDA. The set_dgl_env.sh does not apply to Docker. I've updated the README and the set_dgl_env.sh. If you plan to use dgl, we suggest:

1) [Install CUDA](https://developer.nvidia.com/cuda-11.1.0-download-archive)

or 
2) Set up an environment variable to use CPU instead of GPU

`$ export CUDA_VISIBLE_DEVICES=''`

After that you may need to add your dgl path to `LD_LIBRARY_PATH`. Please let us know if either option works for you. Thanks.

**Comment by mauvais2** [comment]
Close this old issue. Please submit a new one if you run into similar issue. Thanks.
